export type Enfant = {
  Etd_Id: string,
  Pers_Id: string,
  Etd_Matricule: string,
  Ttr1_Id: string,
  LienTtr1Etd_Id: string,
  Ttr2_Id: string,
  LienTtr2Etd_Id: string,
  Sex_Id: string,
  Pays_Id: string,
  PersTyp_Id: string,
  Pers_Nom: string,
  Pers_Prenom: string,
  Pers_Photo: string,
  Pers_DateNaissance: Date,
  Pers_CinouPass: string,
  PersRecrut_Id: string,
  SecteurEnum_Id: string,
  StatutTravailEnum_Id: string,
  FonctionEnum_Id: string,
  EntrepEnum_Id: string,
  Crd_AdrLigne1: string,
  Crd_AdrLigne2: string,
  Crd_Ville: string,
  Crd_CodePostal: string,
  Crd_Pays: string,
  Crd_TelFixe1: string,
  Crd_TelFixe2: string,
  Crd_Cell1: string,
  Crd_Cell2: string,
  Crd_AdessCouriel1: string,
  Crd_AdessCouriel2: string,
  Crd_X: 0,
  Crd_Y: 0,
  Crd_LieuDeNaissance: string,
  Nation_Id: string,
  ARPers_Nom: string,
  ARPers_Prenom: string,
  ARCrd_LieuNaissance: string,
  ecole ?: string,
  specialite ?: string,
  semester ?: string
}
